name: FastAPI and Postman Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman
        run: npm install -g newman

      - name: Start FastAPI Locally
        run: |
          # Install any required dependencies
          pip install -r requirements.txt

          # Start your FastAPI application (assuming your main FastAPI file is app.py)
          uvicorn exercice2:api --reload
        background: true

      - name: Wait for FastAPI to Start
        run: sleep 10 # Adjust as needed to allow time for the FastAPI app to start

      - name: Run Postman Tests
        run: newman run postman_tests/test_api_user.json

